spring.application.name=demo
# URL de la base de données (on utilise la base 'postgres' par défaut pour tester)
spring.datasource.url=jdbc:postgresql://localhost:5432/costumfit_db

# Tes identifiants
spring.datasource.username=postgres
spring.datasource.password=pastgres

# Le driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel : Hibernate va créer/mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update

# Optionnel : Affiche les requêtes SQL dans la console (pratique pour débugger)
spring.jpa.show-sql=true